FROM python:3.11-slim AS base

WORKDIR /app

COPY requirements/train.txt requirements/train.txt

RUN pip install --no-cache-dir -r requirements/train.txt


FROM base AS training

COPY src/ src/
COPY configs/ configs/

ENV PYTHONUNBUFFERED=1
ENV CONFIG_PATH=/app/configs/training_config.yaml

ENTRYPOINT ["python", "-m", "src.train"]